### ISSUE TITLE
How can i fix the mail issue?

### ISSUE THREAD

**Issue by n-for-all** [jvoisin/snuffleupagus#483] opened 2024-03-22 17:03 UTC
I am using the default configuration, even if i remove the mail rule in the default rules, i still get the logs below:

```
[snuffleupagus][0.0.0.0][config][log]   - 3 parameter's name: 'additional_headers'-/public_html/vendor/phpmailer/phpmailer/src/PHPMailer.php-874
[snuffleupagus][0.0.0.0][config][log]   - 4 parameter's name: 'additional_params'-/public_html/vendor/phpmailer/phpmailer/src/PHPMailer.php-874
[snuffleupagus][0.0.0.0][config][log]   - 0 parameter's name: 'to'-/public_html/vendor/phpmailer/phpmailer/src/PHPMailer.php-874
[snuffleupagus][0.0.0.0][config][log]   - 1 parameter's name: 'subject'-/public_html/vendor/phpmailer/phpmailer/src/PHPMailer.php-874
[snuffleupagus][0.0.0.0][config][log]   - 2 parameter's name: 'message'-/public_html/vendor/phpmailer/phpmailer/src/PHPMailer.php-874
[snuffleupagus][0.0.0.0][config][log] It seems that you are filtering on a parameter 'additional_parameters' of the function 'mail', but the parameter does not exists.-/public_html/vendor/phpmailer/phpmailer/src/PHPMailer.php-874
```

I am using php8.3

**Comment by jvoisin** [comment] 2024-03-24 16:42
You can change the rule `sp.disable_function.function("mail").param("additional_parameters").value_r("\\-").drop();` to `sp.disable_function.function("mail").param("additional_params").value_r("\\-").drop();`.

The root cause is php changing parameter names from time to time, this time from `additional_parameters` to `additional_params` in [`mail`](https://www.php.net/manual/en/function.mail.php).

This should be fixed by 6fe3815271a50329a2ba0aa492bb2c9a9820b962

**Closed by jvoisin** 2024-03-24 16:42 UTC
