### ISSUE TITLE
Installing PHP extensions after Snuffleupagus fails in offical PHP docker image

### ISSUE THREAD

**Issue by wedi** [jvoisin/snuffleupagus#341] opened 2020-07-29 19:40 UTC
Hi,
as soon as I have installed Snuffleupagus in my Docker image, installing other extensions fails (tested with redis and imagick).

The following Docker build helps to recreate this issue. When you install redis before Snuffleupagus as in (1) it works but installing other components later will fail as demonstrated in (2).

```Dockerfile
docker build -t snuffy - <<'EOF'
FROM php:7.4-fpm-alpine

ARG PHP_REDIS_VERSION=5.3.1
ARG SNUFFLEUPAGUS_VERSION=0.5.1

RUN set -eux; \
    apk --no-cache add \
        pcre \
        pcre-dev \
        redis \
        ; \
    mkdir -p /usr/src/php/ext/snuffleupagus; \
    curl -fsSL https://github.com/jvoisin/snuffleupagus/archive/v$SNUFFLEUPAGUS_VERSION.tar.gz \
        | tar xz -C /usr/src/php/ext/snuffleupagus --strip-components=2 snuffleupagus-$SNUFFLEUPAGUS_VERSION/src; \
    \
    mkdir -p /usr/src/php/ext/redis; \
    curl -fsSL https://github.com/phpredis/phpredis/archive/$PHP_REDIS_VERSION.tar.gz \
        | tar xz --strip-components=1 -C /usr/src/php/ext/redis; \
    \
    sed -i 's/set -e/set -ex/' /usr/local/bin/docker-php-ext-install; \
    sed -i 's/set -e/set -ex/' /usr/local/bin/docker-php-ext-enable; \
    sed -i 's/set -e/set -ex/' /usr/local/bin/docker-php-ext-configure;

RUN  set -eux; \
    # (1) Works
    #docker-php-ext-install redis snuffleupagus; \
    # (2) Breaks
    docker-php-ext-install snuffleupagus redis; \
    \
    apk del --no-network pcre-dev;
EOF
```

I added `set -x` to the [helper scripts](https://github.com/docker-library/php/tree/master/7.4/alpine3.12/fpm) built into the official PHP base image so you can more easily track what's happening. I omited the lengthy output because it's a matter of copy and paste to reproduce this issue. I'm happy to add it on request.

**Comment by jvoisin** [comment] 2020-08-02 09:35
@wargio Do you want to take a look at this one?
Otherwise, I'll give it a try in a couple of days.

**Comment by wargio** [comment] 2020-08-02 11:52
i'll see what i can do today

**Comment by wargio** [comment] 2020-08-02 14:00
```
php -c /usr/local/etc/php/php.ini-development 
PHP Fatal error:  [snuffleupagus][0.0.0.0][config] Invalid configuration file in Unknown on line 0

Fatal error: [snuffleupagus][0.0.0.0][config] Invalid configuration file in Unknown on line 0
```

**Comment by wargio** [comment] 2020-08-02 14:01
the issue is that you are trying to enable (and run) sp without a proper configuration @wedi

**Comment by jvoisin** [comment] 2020-08-06 12:40
Closing this one in favour of #239

**Closed by jvoisin** 2020-08-06 12:40 UTC
Labels: question

**Comment by wedi** [comment] 2020-09-18 23:54
Thanks for looking into this, @wargio! I did not get that _"Invalid configuration file"_ means that snuffleupagus is missing it's configuration. It works flawlessly when adding the required configuration prior to installing, e.g. 

```
RUN  set -eux; \
    echo -e "sp.configuration_file = ''\nsp.allow_broken_configuration = 1" > $PHP_INI_DIR/conf.d/50-snuffleupagus.ini; \
    docker-php-ext-install snuffleupagus redis;
```

So, #239 solves this issue indeed.
