### ISSUE TITLE
Can't make 0.7.0 debian package (Buster/7.3)

### ISSUE THREAD

**Issue by illydone** [jvoisin/snuffleupagus#393] opened 2021-05-11 10:06 UTC
Hi
When trying to make a package, I have an error during test target.

```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   15
---------------------------------------------------------------------

Number of tests :  388               344
Tests skipped   :   44 ( 11.3%) --------
Tests warned    :    3 (  0.8%) (  0.9%)
Tests failed    :   73 ( 18.8%) ( 21.2%)
Expected fail   :    2 (  0.5%) (  0.6%)
Tests passed    :  266 ( 68.6%) ( 77.3%)
---------------------------------------------------------------------
Time taken      :   36 seconds
=====================================================================
```

And finally I get:
```
make[3]: *** [Makefile:133: test] Error 1
make[3]: Leaving directory '/home/user/snuffleupagus-0.7.0/src'
make[2]: *** [debian/rules:31: override_dh_auto_test] Error 2
make[2]: Leaving directory '/home/user/snuffleupagus-0.7.0'
make[1]: *** [debian/rules:11: build] Error 2
make[1]: Leaving directory '/home/user/snuffleupagus-0.7.0'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make: *** [Makefile:59: debian] Error 2
```

When commenting the commands in debian/rules under override_dh_auto_test target, packages are generated... but tests aren't made.

**Comment by jvoisin** [comment] 2021-05-11 10:22
I can't reproduce the issue locally on Ubuntu :/

@wargio can you take a look?

**Comment by wargio** [comment] 2021-05-11 15:43
i'll check on the docker image.

**Comment by wargio** [comment] 2021-06-17 21:16
i can't reproduce.
i have uploaded the debs here: https://github.com/jvoisin/snuffleupagus/releases/tag/v0.7.0

**Comment by illydone** [comment] 2021-06-23 06:53
I'll make another try with a fresh install.

Thanks for the packages.

**Comment by wargio** [comment] 2021-08-02 18:34
can we close this?

**Comment by illydone** [comment] 2021-08-03 08:40
You can"t reproduce the problem so you can close it.

However, I still can't compile it with freshly installed debian 10. As I can bypass the tests or download the pre compiled packages, I have a solution. ;)

**Comment by wargio** [comment] 2021-08-03 09:27
Perfect. we need to fix this anyway.

**Closed by wargio** 2021-08-03 09:27 UTC
Labels: build system
